### ISSUE TITLE
Database Error: Driver not loaded Driver not loaded

### ISSUE THREAD

**Issue by emiliobruno** [enricofer/postgisQueryBuilder#15]
Ciao Enrico,

When I select any database from the  "Postgres Connection" dropdown list in postgisQueryBuilder
 plugin, I get the following errror : "Database Error: Driver not loaded Driver not loaded."
What is missing im my system  ?
I access all postgis tables and features normally in QGIS environment.
My system: 
->Ubuntu 14.04.2 LTS 
->Kernel 3.13.0-55-generic
-> Qgis 2.8;
->/usr/bin/python2.7: Python 2.7.6
-> Postgresql:9.1
-> "POSTGIS="2.1.7 r13414" GEOS="3.4.2-CAPI-1.8.2 r3921" PROJ="Rel. 4.8.0, 6 March 2012" GDAL="GDAL 1.11.2, released 2015/02/10" 
->python-psycopg2 installed
->libpq-dev installed

Grazie mille,

Emilio Bruno

**Comment by enricofer** [comment]
I can't understand why. I am using Ubuntu with a quite similar configuration and I get no error.
But searching I found this: https://forum.qt.io/topic/5549/solved-error-driver-not-loaded-driver-not-loaded-on-ubuntu
Perhaps, for unknown reason, you have not properly installed the sql library: so try
`sudo install libqt4-sql-psql`
Let me know if it resolvs.

Regards

**Comment by emiliobruno** [comment]
Ciao Enrico,

Ho installato |libqt4-sql-psql| e il sistema ha funzionato correttamente.

Grazie,

Emilio


On 23-06-2015 05:08, enrico ferreguti wrote:
>
> I can't understand why. I am using Ubuntu with a quite similar 
> configuration and I get no error.
> But searching I found this: 
> https://forum.qt.io/topic/5549/solved-error-driver-not-loaded-driver-not-loaded-on-ubuntu
> Perhaps, for unknown reason, you have not properly installed the sql 
> library: so try
> |sudo install libqt4-sql-psql|
> Let me know if it resolvs.
>
> Regards
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/enricofer/postgisQueryBuilder/issues/15#issuecomment-114399403>.
>


--

**Comment by enricofer** [comment]
Bene. Almeno un problema risolto. Ciao.

**Comment by dijkstra** [comment]
Yup, that was the problem. Thank you enricofer.

**Comment by enricofer** [comment]
Thanks, all the best.

**Comment by bvl2016** [comment]
Hello Enricofer,
I am now using this plugin with Linux Mint 20 (Ulyana), and this error is still happened (QGIS 3.10). However, I have already installed the ODBC driver. Could you check please?
Thank you.

**Comment by enricofer** [comment]
Could you provide exception trace?
