### ISSUE TITLE
SQL code bug

### ISSUE THREAD

**Issue by procino** [enricofer/postgisQueryBuilder#18]
Dear all,
I'm using:
a) qGIS 2.18.24 on Window 10
b) db connection to postgres 9.3 / postgis 2.1.2 

If I build spatial query using two layer within db connection (b) the sql generated by postgresPlugin contain "blank" value after the table name so the run query to fail.

Is there a patch?

best regards
Giuseppe P.

**Comment by enricofer** [comment]
Is this resolving https://github.com/enricofer/postgisQueryBuilder/commit/01001d79d25d2db76602d59e6675e81d3347a2e4

**Comment by enricofer** [comment]
Any feedback?

**Comment by procino** [comment]
Hi Enrico,
the bug didn't resolve.
The SQL after plugin apdate is the following. In the last row there is a blank space.
SELECT row_number() OVER () AS ogc_fid,
       ST_Union("sez2001".geom,"poligono_prova".geom) AS the_geom
FROM "sdo_carto"."sez2001",
     "sdo_carto"."poligono_prova  "

**Comment by procino** [comment]
Are there updates?

**Comment by enricofer** [comment]
https://github.com/enricofer/postgisQueryBuilder/commit/fe2e50b0df6c94df94abe33fa079d839f75e9b4a

**Comment by enricofer** [comment]
fixed on QGIS3: https://github.com/enricofer/postgisQueryBuilder/commit/42555fe4599488801f4dc9f012369abe947f674b

**Comment by procino** [comment]
Hi Enrico,
I'm using qGIS 2.18.24. Is the bug fixed on qGis 2.18 too?

**Comment by enricofer** [comment]
yes, it should be.

**Comment by procino** [comment]
Ok thank you. It works fine.
